Develop login
alen-alen/PhpYourAdmin pull request #1
Opened 2021-05-10 10:48 UTC by alen-alen

2021-05-10 13:34 UTC, internalle commented on app/Helpers/Cookie.php
> +        $time = time() + 64000;
Should we have a parameter for setting the expiry of the cookie ?

2021-05-10 13:36 UTC, internalle commented on app/Helpers/Cookie.php
> +    public static function isSet($key)
You can probably name the method exist($key),

Other think you can improve is you can use return isset($_COOKIE[$key]), with this you will shorten the code since there is no need separate if else

2021-05-10 13:38 UTC, internalle commented on app/Helpers/Hash.php
> +    public static function encrypt($string)
You can probably add return types to all the methods that doesn't have and also comments

2021-05-10 13:39 UTC, internalle commented on app/Helpers/Session.php
> +    public static function display()
Why a session method would print anything ?

2021-05-10 13:39 UTC, internalle commented on app/Helpers/UserFile.php
> +    const FILE_PATH = 'users.txt';
You might get the filename from .env so it can be configurable

2021-05-10 13:41 UTC, internalle commented on app/Helpers/UserFile.php
> +        file_put_contents(self::FILE_PATH, $encryptNewStrig);
Maybe you can add these methods for working with files in a generic PHP class

2021-05-10 13:43 UTC, internalle commented on app/Models/User.php
> +    public function connectToDb($credentials)
This should be probably deleted if its not used :)

2021-05-10 13:44 UTC, internalle commented on app/views/parcels/footer.php
> +<?php session_destroy() ?>
Probably should be done using the Session class you already have

2021-05-10 13:45 UTC, internalle commented on core/App.php
> +
There are extra spaces here

2021-05-10 13:46 UTC, internalle commented on core/App.php
> +    public static  function dd($data)
Empty line is missing above the method. Plus this DD method should probably be part of some helper class

2021-05-10 13:48 UTC, internalle commented on core/Request.php
> +    public static function method()
You can add methods like isPost or isGET in this class it will help you to do the checks.

Also you can add method for getting the data from the request

2021-05-10 13:50 UTC, internalle commented on core/database/Connection.php
> +    public static function make()
Make this an actual object instance instead of being static. When you boot the app you make an instance and make connection, when you destruct the application you call connection close method

2021-05-10 13:50 UTC, internalle commented on core/helpers.php
> +function sessionGet($key, $secondKey = false)
This should go into session class instead of having helper methods

2021-05-11 07:28 UTC, davorminchorov commented on app/Helpers/Hash.php
> +    public static function encrypt($string)
And parameter type hints.

2021-05-11 07:43 UTC, davorminchorov requested changes
There are a few tweaks that can be done so check all of the comments.

2021-05-11 07:43 UTC, davorminchorov commented on app/Helpers/Hash.php
> +        $simple_string = $string;
Variable and method names should be camelCase based on the PSR code styling rules.

2021-05-11 07:43 UTC, davorminchorov commented on core/App.php
> +        if ($data == null) {
Always use === for these types of checks.

2021-05-11 07:43 UTC, davorminchorov commented on core/App.php
> +        if ($data == null) {
Alternative solution can be !$data in this case.

2021-05-11 07:43 UTC, davorminchorov commented on core/Env/DotEnv.php
> +        // die(var_dump($path));
You can remove this line.

2021-05-11 07:43 UTC, davorminchorov commented on core/Env/DotEnv.php
> +            list($name, $value) = explode('=', $line, 2);
You can use array destructuring [] instead of list here.

2021-05-11 11:58 UTC, davorminchorov commented on .env copy
> +ECNRYPTION_KEY=key
You have a typo here: ECNRYPTION_KEY -> ENCRYPTION_KEY

2021-05-11 12:03 UTC, davorminchorov commented on core/Router.php
> +    public function load($file)
you are missing type hints, return types and docblocks here in this class.

2021-05-11 13:12 UTC, davorminchorov approved these changes
Looks good.

2021-05-12 07:10 UTC, internalle approved these changes

2021-05-12 07:15 UTC, merged