Develop left side
alen-alen/PhpYourAdmin pull request #2
Opened 2021-05-17 07:28 UTC by alen-alen

2021-05-17 07:49 UTC, davorminchorov requested changes
I found a few issues, check them out and figure out how they can be fixed.

2021-05-17 07:49 UTC, davorminchorov commented on app/Controllers/DashboardController.php
> +      Route::redirect('');
It's confusing when you don't need to pass a value to a method and that value can be a default. so I would suggest the following:
Create a separate method called something like `redirectHome()` which will redirect to home if you don't need to pass any strings to it, instead of passing an empty string like you did here.

2021-05-17 07:49 UTC, davorminchorov commented on core/Router.php
> +        $router =$this;
Add space here between = and $this

2021-05-17 07:49 UTC, davorminchorov commented on core/database/Query.php
> +        $sql = "SELECT * FROM $table";
You are missing bindings here. :table instead of $table for security reasons.

2021-05-17 07:49 UTC, davorminchorov commented on core/database/Query.php
> +        $sql = "SHOW COLUMNS FROM $table;";
You are missing bindings here. :table instead of $table for security reasons.

2021-05-17 07:49 UTC, davorminchorov commented on core/database/Connection.php
> +        if (self::$pdo === null) {
you can also do `!self::$pdo` here.

2021-05-17 07:49 UTC, davorminchorov commented on core/database/Connection.php
> +        if (self::$pdo !== null) {
you can also do self::$pdo here.

2021-05-17 07:49 UTC, davorminchorov commented on public/js/datatablse.js
> +    $('#myTable').DataTable();
This file is misspelled datatablse.js -> /datatable.js
As an alternative, you can also name it based on what it actually displays rather than a generic file name or even ID #myTable just so that is more understandable.

2021-05-17 07:49 UTC, davorminchorov commented on core/database/Query.php
> +
You can remove these empty spaces here.

2021-05-17 07:49 UTC, davorminchorov commented on core/database/Connection.php
> +        if (isset($_GET['db'])) {
I would suggest for you to pass the value via the constructor rather than using the GET Request parameters here. 

Also, don't forget that you have a Request class that you can use for getting GET or POST request parameters.

2021-05-17 08:44 UTC, internalle commented on app/Controllers/DatabaseController.php
> +    if ($_GET) {
Would suggest to create a helper class that checks the type of the request as $request->isPost() or $request->isGet()

2021-05-17 08:44 UTC, internalle commented on app/Controllers/DatabaseController.php
> +/**
The comment is not indented properly :)

2021-05-17 08:44 UTC, internalle commented on app/Helpers/Route.php
> +                if ($key === 0) {
You might even shorten this one for example:

$path = ($key === 0) ? "?" : "&";
$path .= "{$param[0]}={$param[1]}";

2021-05-17 08:44 UTC, internalle commented on app/Requests/LoginRequest.php
> +
We don't need an empty line here for example :)

2021-05-17 08:44 UTC, internalle commented on app/views/parcels/dashboard.php
> +                    <option <?= isset($_GET['db']) && $db['Database'] === $_GET['db'] ? 'selected' : '' ?> value="<?= $db['Database'] ?>"><?= $db['Database'] ?></option>
Instead of directly checking $_GET['db'] you could create a class that leverages that functionality of getting POST or GET params something similar that. This is not required but its good practice to work with objects.  

For example request->post()->get('fieldName') or request->get()->get('fieldName') or something similar. You can check how Laravel requests work or Codeigniter or any other framework

2021-05-17 08:44 UTC, internalle commented on core/Request.php
> +        // die(var_dump(( $_SERVER )));
Try to deleted things if you don't need them

2021-05-18 09:42 UTC, davorminchorov requested changes
I found a few more issues that can be fixed with this PR.

2021-05-18 09:42 UTC, davorminchorov commented on app/Controllers/DatabaseController.php
> +  public function store($request)
parameter type hint and return type are missing here.

2021-05-18 09:42 UTC, davorminchorov commented on core/Request.php
> +        return $_SERVER['REQUEST_METHOD'] === 'POST' ? true : false;
Just a tip: You don't actually need `? true : false;` because it will automatically be determined based on the condition. 

Same as above.

2021-05-18 09:42 UTC, davorminchorov commented on core/Router.php
> +        // die(var_dump($controller));
You can remove this.

2021-05-18 09:42 UTC, davorminchorov commented on core/Router.php
> +        Route::redirect('database/dashboard');
Why is there a redirect here if you are throwing an exception? The redirect would be in the catch block

Also, you can use the Route::HOME_ROUTE class constant for the name wherever you need it just so that you don't duplicate yourself.

2021-05-18 09:42 UTC, davorminchorov commented on core/database/Query.php
> +        $sql = "SHOW COLUMNS FROM $table";
You are missing bindings here. :table instead of $table for security reasons.

2021-05-18 09:42 UTC, davorminchorov commented on core/database/Query.php
> +        $sql = "CREATE DATABASE $dbName CHARACTER SET $charset COLLATE $collate";
Are these values validated?

2021-05-18 09:42 UTC, davorminchorov commented on core/database/Query.php
> +    public function createDatabase($dbName, $charset, $collate)
parameter type hints and return type missing here.

2021-05-18 09:42 UTC, davorminchorov commented on core/database/Query.php
> +        $stmt = $this->pdo->prepare($sql);
$stmt -> $statement - Avoid using abbreviations when naming variables and methods, it's a bad practice and it's hard to read / understand.

2021-05-18 09:42 UTC, davorminchorov commented on core/database/Query.php
> +        $sql = "SHOW COLLATION WHERE ID=:id";
You can add spaces between the `=` sign.

2021-05-18 09:42 UTC, davorminchorov commented on app/Controllers/DatabaseController.php
> +    return $this->view('home', compact('databases'));
You need only one return view at the end, just pass the data once and update the view with the checks. No need to duplicate the code 3 times, all you need is the correct variables assigned in the if statements.

2021-05-19 08:31 UTC, davorminchorov approved these changes
Looks good.

2021-05-19 11:36 UTC, merged