Develop di container
alen-alen/PhpYourAdmin pull request #5
Opened 2021-05-28 10:01 UTC by alen-alen

2021-05-28 10:24 UTC, internalle requested changes

2021-05-28 10:24 UTC, internalle commented on app/Auth/UserAuth.php
> +    public function __construct(
You might also add comment above the constructor like:

    /**
     * Translate constructor.
     * @param Cookie $cookie
     * @param Route $route
     * @param UserFile $userFile
     * @param Query $query
     */

2021-05-28 10:24 UTC, internalle commented on app/Auth/UserAuth.php
> +    public Route $route;
The Route class should be probably named "Router" since its used for routing, and its not only holding a specific route

2021-05-28 10:24 UTC, internalle commented on app/Controllers/ApiController.php
> +    public function getTables()
The comment says that this method returns array, but this method does not return anything, so it should probably be void

2021-05-28 10:24 UTC, internalle commented on app/Auth/UserAuth.php
> +    public Cookie $cookie;
/**
     * @var Cookie $cookie
     */
     
     Comments are missing above the class vars

2021-05-28 10:24 UTC, internalle commented on app/Controllers/DatabaseController.php
> +  public function userQuery()
You can probably add :void to all of these methods that doesnt return anything :)

2021-05-28 10:24 UTC, internalle commented on core/App.php
> +            die($e->getMessage());
Should we die here ? Since previously there was a redirect ?

2021-05-28 10:24 UTC, internalle commented on core/config.php
> +        return Connection::getInstance(new Request(new Session(), new Cookie()),new UserFile());
empty space is neded after new Cookie()),

2021-05-28 10:24 UTC, internalle commented on core/database/Connection.php
> +            return  $this->createConnection();
There is an extra empty space infront $this->createConnection

2021-05-28 10:24 UTC, internalle commented on core/database/Connection.php
> +            "mysql:host={$this->config['host']};dbname={$this->request->parameter('db')}" :
You might shoren this like this. No need to duplicate the "mysql:host={$this->config['host']};" twice :)

$dns = "mysql:host={$this->config['host']};";
$dns .= $this->request->has('db') ? "dbname={$this->request->parameter('db')}" : "";

2021-05-28 10:24 UTC, internalle commented on core/database/Query.php
> +                new \PDO("mysql:host=$host", $username, $password);
How do you know if you have a networking problem or its user/pass combo mistaken ?

2021-05-28 10:24 UTC, internalle commented on core/database/Query.php
> +            die(var_dump($statement->errorInfo()[2]));
This should be removed probably :)

2021-05-31 11:30 UTC, davorminchorov approved these changes
Looks good.

2021-05-31 11:30 UTC, davorminchorov commented on app/File/UserFile.php
>       * @return void|false
Just a tip: try to always return a single type of data from a method, to avoid confusion like this one. In this case, you can add `return true;` at the bottom of the method.
Try to convert the types, if the original return type should be an array, try to return an empty array instead of false (example).
This will help you to not do additional type checks outside of the method itself and you will have less possible bugs in the code.

2021-05-31 11:30 UTC, davorminchorov commented on app/Helpers/Session.php
> +        if ($this->active === true) {
this can be simplified to `if($this->active)` because the property active should either be true or false.

2021-05-31 11:30 UTC, davorminchorov commented on app/Models/MysqlUser.php
> +    public function __construct($username, $host, $password = null, $type)
Always put the parameters with default values last, just so that you don't have to add the default value to skip a parameter.

2021-05-31 11:30 UTC, davorminchorov commented on app/Requests/MysqlUserRequest.php
> +    private Route $route;
You are missing a docblock here.

2021-05-31 11:30 UTC, davorminchorov commented on app/routes.php
> +$router->get('', 'DatabaseController@dashboard');
shouldn't this be `'/'`? It looks weird when it's an empty string.

2021-05-31 11:30 UTC, davorminchorov commented on core/database/Query.php
> +            // die(var_dump($statement->errorInfo()[2]));
You can remove this line.

2021-06-02 08:52 UTC, merged